### PR TITLE
Add schemas generator

### PR DESCRIPTION
**Pull request by lstocchi**

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
Funny because I did the same yesterday. Looks almost similar but seems you removed the customization for specific K8S based types, is this on purpose ?
Also you're missing Configuration and Route

**Comment by lstocchi** [comment]
> Also you're missing Configuration and Route

Configuration and route are really necessary? They are created by knative when user create a new service, so why do we need a schema for them?

> Funny because I did the same yesterday. Looks almost similar but seems you removed the customization for specific K8S based types, is this on purpose ?

You mean `k8s.io/apimachinery/pkg/apis/meta/v1`?  During building `go` told me it wasn't used

**Comment by jeffmaury** [comment]
Yes because you removed https://github.com/redhat-developer/intellij-tekton/blob/master/releng/gen.go#L35

**Comment by lstocchi** [comment]
What about configuration and route schema? Do i need to add them? @jeffmaury

**Comment by jeffmaury** [comment]
I would add them as we may allow viewing in editor one point in time

**Comment by lstocchi** [comment]
Added @jeffmaury . Please check if it is ok

**Review by jeffmaury — APPROVED** [review]
LGTM.

**Pull request merged**
