### PR TITLE
prepare for first release

### PR DESCRIPTION
**Pull request by lstocchi**
Signed-off-by: Luca Stocchi <lstocchi@redhat.com>

### CODE REVIEW

**Review by evidolob — APPROVED** [review]
LGTM

**Review by jeffmaury — CHANGES_REQUESTED** [review]
According to semver and @joshuawilson version should be 0.1.0. Would you mind updating this PR ?

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Latest comment by JetBrains as to remove the Overview header in the description

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
