### PR TITLE
refactor: Increase code coverage

### PR DESCRIPTION
**Pull request by lstocchi**
I have written some tests that covers almost everything except the things related to the create/update actions and serializators as i have opened PRs that i have to work on related to these things so i'll write the missing tests while working on those enhancements.

The naming rule used for tests is MethodToBeTested_SomeContextThatHasToBeTrueToObtainTheResult_FinalResultToBeAchieved (e.g: ActionPerformed_EventFromToolbar_Refresh). I hope this makes tests clearer.

### CODE REVIEW

**Comment by joshuawilson** [comment]
It would be better if you make a commit and PR for each test so that it can be reviewed. Currently 45 files, will be hard to review.

**Comment by lstocchi** [comment]
> It would be better if you make a commit and PR for each test so that it can be reviewed. Currently 45 files, will be hard to review.

It seems scarier than what it really is. BTW I already talked with Jeff and Yevhen so this is why it's all in one PR

**Comment by joshuawilson** [comment]
> > It would be better if you make a commit and PR for each test so that it can be reviewed. Currently 45 files, will be hard to review.
> 
> It seems scarier than what it really is. BTW I already talked with Jeff and Yevhen so this is why it's all in one PR

It is not scary that it is so large. It statistically unlikely to have a reviewer give a thorough review. It is harder to find mistakes. It is also harder to track down changes later when you are looking for one that broke something. I'm not going to say you must refactor it, only that it would be wise to do so.

**Review by evidolob — APPROVED** [review]
LGTM

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
