### PR TITLE
allow to update knative service from IDE (#6)

### LINKED ISSUE #6: Update service
As a user, I should be able to update a service.

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #6 
It needs https://github.com/redhat-developer/intellij-common/pull/47 to work

### CODE REVIEW

**Review by evidolob — APPROVED** [review]
It works well.
I just wondering is there any way to avoid showing this dialog:
Screenshot 2021-03-23 at 10 35 58

**Comment by lstocchi** [comment]
> I just wondering is there any way to avoid showing this dialog:
> Screenshot 2021-03-23 at 10 35 58

When do you see this? When you try to edit a read-only resource (revision) or an editable resource (service) or both?

**Comment by evidolob** [comment]
>When do you see this? When you try to edit a read-only resource (revision) or an editable resource (service) or both?

First time, when I try to edit editable resource (service).

**Comment by evidolob** [comment]
>When do you see this? When you try to edit a read-only resource (revision) or an editable resource (service) or both?

First time, when I try to edit editable resource (service).

**Comment by lstocchi** [comment]
> > When do you see this? When you try to edit a read-only resource (revision) or an editable resource (service) or both?
> 
> First time, when I try to edit editable resource (service).

That's really bad and annoying. I don't have this issue on Linux but Andrè faced this too. So maybe it's a Mac issue. He is currently working on the same stuff on IJ K8s and hopefully he will fix this. In the meantime i'll try to search around and see if i can find something.

**Comment by lstocchi** [comment]
@evidolob could you please re-test this (by updating commons) and confirm you don't see the `non-project files protection` dialog again? Andrè found a fix for it https://github.com/redhat-developer/intellij-common/pull/52 , if you could confirm it works for you as well we will be sure it works

**Comment by evidolob** [comment]
@lstocchi Yes, now edit works without that dialog.

**Review by jeffmaury — APPROVED** [review]
LGTM. I just noticed that the fieldsV1 has highlighted we should check if we have the same for Tekton

**Pull request merged**
