### PR TITLE
fix: updated icons for knative resources (#131)

### LINKED ISSUE #131: Update icons
As agreed with Mohit we're going to use icons similar to those used in tekton. The same labels used in the openshift console.

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #131 

I copied the color from the openshift console. Let me know if i need to change anything? cc @sudhirverma 
image

### CODE REVIEW

**Comment by mohitsuman** [comment]
@lstocchi Looks good to me. Just a few minor changes.

- For the badge `KSVC`, we need to increase the margin/padding between the wordings and the badge. 

Does the colour look good in the Light colour theme on IntelliJ?

**Comment by lstocchi** [comment]
@mohitsuman is it better? Below a pic with the IJ white theme

image

image

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by mohitsuman — APPROVED** [review]
LGTM

**Pull request merged**
