### PR TITLE
chore: add dependency to kubernetes plugin (#44)

### PR DESCRIPTION
**Pull request by lstocchi**
New IJ k8s release allows to switch namespace/project :rocket:

### CODE REVIEW

**Comment by joshuawilson** [comment]
How does it depend on the kubernetes plugin?

**Comment by lstocchi** [comment]
The Knative plugin only shows the current active namespace and you don't have any way to switch namespace/cluster. By adding this dependency, when you install knative, you also install IJ k8s so you can use that one to switch namespace/cluster

**Comment by joshuawilson** [comment]
While I do understand the value of it, is it required to run the knative plugin? 

I might miss understand `dependency` in intellij, I would think that it means without it the plugin will not run. If it runs but is less useful then would it not be something for the README?

**Comment by lstocchi** [comment]
I would go this way and then remove the dependency if we receive some complains. Very few ppl read the README and even if they do i'm pretty sure they will end up installing the wrong k8s plugin (there is one from Jetbrains in the marketplace). 
If you work with knative, you work with kubernetes, so it's not like we are installing something which is not needed. You can take advantage of the k8s plugin to read logs, create/edit resources which doesn't belong to knative, schemas ... and this can also be considered a marketing move to make our k8s plugin be known in the IJ community.

**Comment by joshuawilson** [comment]
I can agree with that logic.

**Review by joshuawilson — APPROVED** [review]

**Review by evidolob — APPROVED** [review]

**Pull request merged**
