### PR TITLE
fix: encoding issue when executing tasks (#169)

### LINKED ISSUE #169: Encoding issue in the build window on Windows
knative

### PR DESCRIPTION
**Pull request by lstocchi**
It resolves #169 . Followed what's done in common. Could you please verify if it fixes your issue? If not, any suggestion? @jeffmaury  Thanks

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
Did not fix the problem on Windows. Might be an encoding issue on the CLI side

**Comment by lstocchi** [comment]
> Did not fix the problem on Windows. Might be an encoding issue on the CLI side

:/ Can you please give it a try to see if the issue is there? If not, i'll try to investigate more on it

**Comment by jeffmaury** [comment]
Tried the same command that is launched by the plugin in both the Windows CMD and Git bash.exe and got no encoding issues. It seems to be related to ansi escape characters as the data that is corrupted is printed in blue by the CLI.

Also tried to run the same command in the IJ terminal (with launches git bash.exe) causes the ansi characters not to be correctly handled but not in the same way as the plugin

**Comment by lstocchi** [comment]
@jeffmaury The `ColoredProcessHandler` should handle the ansi escape chars. This needs https://github.com/redhat-developer/intellij-common/pull/154 to work

**Comment by adietish** [comment]
Closing this 2 years old pull request.

**Pull request closed without merging**
